# Imagen base (evitar latest)
FROM node:20-alpine

# Directorio de trabajo
WORKDIR /app

# Copiar primero package.json (best practice)
COPY package*.json ./

# Instalar dependencias
RUN npm install --production

# Copiar el resto del proyecto
COPY . .

# Puerto de la app
EXPOSE 3000

# Comando de inicio
CMD ["node", "index.js"]